### PR TITLE
double quotes followed by punctuation bug fixed

### PR DESCRIPTION
**Pull request by gabrielperales**
Fixed regexp for double quotes. Issue [#10](https://github.com/davidmerfield/Typeset/issues/10).

### CODE REVIEW

**Comment by gabrielperales** [comment]
I have **added an editorconfig file**. This file lets you have the same indentation configuration through several editors (I had seen files with different indentations), and **I have also removed some names on functions** which they had inconsistent names and they didn't need to be named functions.

**Comment by gabrielperales** [comment]
I have added some tests. You can run these tests with the command ```npm test``` or with ```npm run watch``` for run tests with the watch flag to watch changes in your tests while you are writing them.

**Comment by davidmerfield** [comment]
Fantastic stuff Gabriel. Thank you very much for your hard work.

**Comment by gabrielperales** [comment]
Hahaha, this is one of the first open source project that I'm working on. I hope everything I'm doing be good. I'm making test of everything to be sure I'm not broken nothing. This first version with browser support is not well designed (and depends on jquery), I think the best way of implement it could be as a jquery plugin. I hope have time to keep working on it.

**Comment by davidmerfield** [comment]
Yeah the jQuery dependency will be removed – it should be quite possible to iterate over text nodes without it! However, this is a solid first step since jQuery matches cheerio's API.

**Pull request merged**
